name: clojars

on:
  push:
    tags:
    - '*'

jobs:
  clojars-deploy:
    runs-on: ubuntu-latest
    steps:
      # useful for Continuous Deployment developing
    - name: validate if it is refs/tags/
      if: startsWith(github.ref,'refs/tags/') != true
      run: exit 1

    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Set TAG value from refs/tags/TAG
      run: echo ::set-env name=GIT_TAG::${GITHUB_REF#refs/tags/}

    - name: Install java
      uses: actions/setup-java@v1
      with:
        java-version: '13.0.1'

    - name: Install clojure
      uses: DeLaGuardo/setup-clojure@2.0
      with:
        tools-deps: 'latest'

    - name: Overwrite pom.xml
      run: |
        sed -i 's;<version/>;<version>${{ env.GIT_TAG }}</version>;' pom.xml
        sed -i 's;<tag/>;<tag>${{ github.sha }}</tag>;' pom.xml
    - name: Update pom.xml
      run: clojure -Srepro -Spom

    - name: Debug pom.xml
      run: cat pom.xml

    - name: Deploy to Clojars
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
      run: mvn -s .m2/settings.xml deploy
