name: Run tests for all environments

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        clojure: [1.9, 1.10]
    steps:
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/setup-node@v1
      if: matrix.clojure == 1.10
      with:
        node-version: '10.x'
    - uses: DeLaGuardo/setup-clojure@2.0
      with:
        tools-deps: latest
    - uses: actions/checkout@v1
    - name: Prepare npm modules for tests
      if: matrix.clojure == 1.10
      run: |
        npm install ws isomorphic-ws
    - name: Run tests
      run: |
        clojure -A:${{ matrix.clojure }}:kaocha:unit
    - name: Upload test coverage results
      if: matrix.clojure == 1.10
      run: |
        bash <(curl -s https://codecov.io/bash)
    - name: Run JS tests
      if: matrix.clojure == 1.10
      run: |
        clojure -A:${{ matrix.clojure }}:kaocha:unit-cljs
